### ISSUE TITLE
Errors when importing the package

### ISSUE THREAD

**Issue by hyperxpizza** [naamancurtis/mongo-go-struct-to-bson#1]
go compiler returns:
```
module github.com/naamancurtis/mongo-go-struct-to-bson@latest found (v0.0.0-20190908144754-b7af57cbdc2a), but does not contain package github.com/naamancurtis/mongo-go-struct-to-bson
```

**Comment by naamancurtis** [comment]
I've not used Go recently, so I'm not overly familar with the new modules syntax, however I've updated the package - 1ff75e8. I now seem to be getting a successful import now with:

```go
import (
	"github.com/naamancurtis/mongo-go-struct-to-bson/mapper"
)
```

Please give it another go and let me know if there are still any issues.

**Comment by naamancurtis** [comment]
I'll close this issue for now as I believe it to be resolved. If it's not then please re-open it and let me know
